In [31]:
import pandas
import numpy
import pygsheets
import datetime
import pytz
import re

In [32]:
# define the excel file to save tables in
current_time = datetime.datetime.now(pytz.timezone('US/Eastern')).strftime("%Y-%m-%d_T%H%M%S")
excel_writer = pandas.ExcelWriter('Global-LNG-Terminals-SummarySheets-'+current_time+'.xlsx')

In [33]:
current_time

'2023-10-12_T114246'

In [54]:
gc = pygsheets.authorize(service_account_env_var='GDRIVE_API_CREDENTIALS')
#spreadsheet = gc.open_by_key('1tcS6Wd-Wp-LTDpLzFgJY_RSNDnbyubW3J_9HKIAys4A')
#spreadsheet = gc.open_by_key('1MrghwBeCz8Tzgua7CWGg_KoXKVZsV7r0kHMYHYqnNTg') # July 2022 terminals version
spreadsheet = gc.open_by_key('1FVuw76YU-jmAzfSWJ2ixwBQB_wXEK9aGCa4Q6OCOUzY') # July 2022 with May 2023 updates for Asia gas tracker

terms_df_orig = spreadsheet.worksheet('title', 'Terminals').get_as_df(start='A2')

# drop any empty/imcomplete rows (those without a wiki page)
terms_df_orig = terms_df_orig.loc[terms_df_orig.Wiki != '']

#get other relevant sheets
owners_df_orig = spreadsheet.worksheet('title', 'Terminal operators/owners (1/3)').get_as_df(start='A2')
owners_df_orig.set_index('ComboID', inplace=True)

parent_metadata_df = spreadsheet.worksheet('title', 'Parent metadata (3/3)').get_as_df(start='A2')
parent_metadata_df.set_index('Parent', inplace=True)

In [55]:
terms_df_orig.replace('--', numpy.nan, inplace=True)

In [56]:
region_df_orig = spreadsheet.worksheet('title', 'Country dictionary').get_as_df(start='A2')
#region_df_agt = region_df_orig.loc[region_df_orig['AsiaGasTracker']=='Yes']

region_df_touse = region_df_orig.copy()
#region_df_agt.copy()

### create specific dataframes for region, country_ratios, owners_df

In [57]:
owners_df_touse = owners_df_orig.loc[owners_df_orig['Country'].isin(region_df_touse['Country'].tolist())]
terms_df_touse = terms_df_orig.loc[terms_df_orig['Country'].isin(region_df_touse['Country'].tolist())]

In [58]:
status_list = ['Proposed', 
               'Construction', 
               'Shelved', 
               'Cancelled', 
               'Operating', 
               'Idle', 
               'Mothballed', 
               'Retired']
country_list = sorted(set(region_df_touse['Country'].tolist()))
region_list = sorted(set(region_df_touse['Region'].tolist()))
subregion_list = sorted(set(region_df_touse['SubRegion'].tolist()))

In [59]:
excel_status_list = ['Proposed', 
                     'Construction', 
                     'In Development (Proposed + Construction)', 
                     'Shelved', 
                     'Cancelled', 
                     'Operating', 
                     'Idle', 
                     'Mothballed', 
                     'Retired']
excel_status_list_with_countries = ['Country']+excel_status_list

In [60]:
# regions - subregions
#############################
# Africa - Sub-Saharan Africa
# Africa - Northern Africa
# Americas - Latin America and the Caribbean
# Americas - North America
# Asia - Southern Asia
# Asia - Western Asia
# Asia - South-eastern Asia
# Asia - East Asia
# Asia - Central Asia
# Europe - Southern Europe
# Europe - Eastern Europe
# Europe - Western Europe
# Europe - Northern Europe
# Oceania	- Polynesia
# Oceania	- Australia and New Zealand
# Oceania	- Melanesia
# Oceania	- Micronesia

### no. export trains by country/region, project status

In [61]:
terms_df_subset = terms_df_touse.copy()[(terms_df_touse['Import/Export']=='Export') & (terms_df_touse['Fuel']=='LNG')]

multiindex_region_subregion = pandas.MultiIndex.from_product([region_list,subregion_list], names=['Region','SubRegion'])

ntrains_by_country = pandas.DataFrame(0, columns=status_list, index=country_list)
ntrains_by_region = pandas.DataFrame(0, columns=status_list, index=multiindex_region_subregion)

print('===country-level calculations===')
for status in status_list:
    print(status)
    terms_df_subset_status = terms_df_subset.copy()[terms_df_subset['Status']==status]
    ntrains_by_country[status] = terms_df_subset_status.groupby('Country').size()

print('===country-level calculations===')
for status in status_list:
    print(status)
    terms_df_subset_status = terms_df_subset.copy()[terms_df_subset['Status']==status]
    ntrains_by_region[status] = terms_df_subset_status.groupby(['Region','SubRegion']).size()

# fille NaN with 0.0
ntrains_by_region = ntrains_by_region.fillna(0)
ntrains_by_country = ntrains_by_country.fillna(0)

ntrains_by_region['In Development (Proposed + Construction)'] = ntrains_by_region[['Proposed','Construction']].sum(axis=1)
ntrains_by_country['In Development (Proposed + Construction)'] = ntrains_by_country[['Proposed','Construction']].sum(axis=1)

ntrains_by_country = ntrains_by_country[excel_status_list]
ntrains_by_region = ntrains_by_region[excel_status_list]

ntrains_by_region.index.names = ['Region','Subregion']
ntrains_by_country.index.name = 'Country'

ntrains_by_region.loc['Total',:] = ntrains_by_region.sum(axis=0).values
ntrains_by_country.loc['Total',:] = ntrains_by_country.sum(axis=0).values

ntrains_by_region = ntrains_by_region.loc[~(ntrains_by_region==0).all(axis=1)]

ntrains_by_region.replace(0,'',inplace=True)
ntrains_by_country.replace(0,'',inplace=True)

ntrains_by_region.to_excel(excel_writer, sheet_name='LNG export trains by region')#, index=False)
ntrains_by_country.to_excel(excel_writer, sheet_name='LNG export trains by country')#, index=False)

===country-level calculations===
Proposed
Construction
Shelved
Cancelled
Operating
Idle
Mothballed
Retired
===country-level calculations===
Proposed
Construction
Shelved
Cancelled
Operating
Idle
Mothballed
Retired

### no. import trains by country/region, project status

In [62]:
terms_df_subset = terms_df_touse.copy()[(terms_df_touse['Import/Export']=='Import') & (terms_df_touse['Fuel']=='LNG')]

multiindex_region_subregion = pandas.MultiIndex.from_product([region_list,subregion_list], names=['Region','SubRegion'])

ntrains_by_country = pandas.DataFrame(0, columns=status_list, index=country_list)
ntrains_by_region = pandas.DataFrame(0, columns=status_list, index=multiindex_region_subregion)

print('===country-level calculations===')
for status in status_list:
    print(status)
    terms_df_subset_status = terms_df_subset.copy()[terms_df_subset['Status']==status]
    ntrains_by_country[status] = terms_df_subset_status.groupby('Country').size()

print('===country-level calculations===')
for status in status_list:
    print(status)
    terms_df_subset_status = terms_df_subset.copy()[terms_df_subset['Status']==status]
    ntrains_by_region[status] = terms_df_subset_status.groupby(['Region','SubRegion']).size()

# fille NaN with 0.0
ntrains_by_region = ntrains_by_region.fillna(0)
ntrains_by_country = ntrains_by_country.fillna(0)

ntrains_by_region['In Development (Proposed + Construction)'] = ntrains_by_region[['Proposed','Construction']].sum(axis=1)
ntrains_by_country['In Development (Proposed + Construction)'] = ntrains_by_country[['Proposed','Construction']].sum(axis=1)

ntrains_by_country = ntrains_by_country[excel_status_list]
ntrains_by_region = ntrains_by_region[excel_status_list]

ntrains_by_region.index.names = ['Region','Subregion']
ntrains_by_country.index.name = 'Country'

ntrains_by_region.loc['Total',:] = ntrains_by_region.sum(axis=0).values
ntrains_by_country.loc['Total',:] = ntrains_by_country.sum(axis=0).values

ntrains_by_region = ntrains_by_region.loc[~(ntrains_by_region==0).all(axis=1)]

ntrains_by_region.replace(0,'',inplace=True)
ntrains_by_country.replace(0,'',inplace=True)

ntrains_by_region.to_excel(excel_writer, sheet_name='LNG import trains by region')#, index=False)
ntrains_by_country.to_excel(excel_writer, sheet_name='LNG import trains by country')#, index=False)

===country-level calculations===
Proposed
Construction
Shelved
Cancelled
Operating
Idle
Mothballed
Retired
===country-level calculations===
Proposed
Construction
Shelved
Cancelled
Operating
Idle
Mothballed
Retired

### capacity (mtpa) of import trains by country/region, project status

In [63]:
terms_df_subset = terms_df_touse.copy()[(terms_df_touse['Import/Export']=='Import') & (terms_df_touse['Fuel']=='LNG')]

multiindex_region_subregion = pandas.MultiIndex.from_product([region_list,subregion_list], names=['Region','SubRegion'])

cap_by_country = pandas.DataFrame(0, columns=status_list, index=country_list)
cap_by_region = pandas.DataFrame(0, columns=status_list, index=multiindex_region_subregion)

print('===country-level calculations===')
for status in status_list:
    print(status)
    terms_df_subset_status = terms_df_subset.copy()[terms_df_subset['Status']==status]
    cap_by_country[status] = terms_df_subset_status.groupby('Country')['CapacityInMtpa'].sum()

print('===country-level calculations===')
for status in status_list:
    print(status)
    terms_df_subset_status = terms_df_subset.copy()[terms_df_subset['Status']==status]
    cap_by_region[status] = terms_df_subset_status.groupby(['Region','SubRegion'])['CapacityInMtpa'].sum()

#fille NaN with 0.0
cap_by_region = cap_by_region.fillna(0)
cap_by_country = cap_by_country.fillna(0)

cap_by_region['In Development (Proposed + Construction)'] = cap_by_region[['Proposed','Construction']].sum(axis=1)
cap_by_country['In Development (Proposed + Construction)'] = cap_by_country[['Proposed','Construction']].sum(axis=1)

cap_by_country = cap_by_country[excel_status_list]
cap_by_region = cap_by_region[excel_status_list]

cap_by_region.index.names = ['Region','Subregion']
cap_by_country.index.name = 'Country'

cap_by_region.loc['Total',:] = cap_by_region.sum(axis=0).values
cap_by_country.loc['Total',:] = cap_by_country.sum(axis=0).values

cap_by_region = cap_by_region.loc[~(cap_by_region==0).all(axis=1)]

cap_by_region.replace(0,'',inplace=True)
cap_by_country.replace(0,'',inplace=True)

cap_by_region.to_excel(excel_writer, 'LNG import capacity by region')
cap_by_country.to_excel(excel_writer, 'LNG import capacity by country')

cap_by_region_import = cap_by_region.copy()

===country-level calculations===
Proposed
Construction
Shelved
Cancelled
Operating
Idle
Mothballed
Retired
===country-level calculations===
Proposed
Construction
Shelved
Cancelled
Operating
Idle
Mothballed
Retired

### capacity (mtpa) of export trains by country/region, project status

In [64]:
terms_df_subset = terms_df_touse.copy()[(terms_df_touse['Import/Export']=='Export') & (terms_df_touse['Fuel']=='LNG')]

multiindex_region_subregion = pandas.MultiIndex.from_product([region_list,subregion_list], names=['Region','SubRegion'])

cap_by_country = pandas.DataFrame(0, columns=status_list, index=country_list)
cap_by_region = pandas.DataFrame(0, columns=status_list, index=multiindex_region_subregion)

print('===country-level calculations===')
for status in status_list:
    print(status)
    terms_df_subset_status = terms_df_subset.copy()[terms_df_subset['Status']==status]
    cap_by_country[status] = terms_df_subset_status.groupby('Country')['CapacityInMtpa'].sum()

print('===country-level calculations===')
for status in status_list:
    print(status)
    terms_df_subset_status = terms_df_subset.copy()[terms_df_subset['Status']==status]
    cap_by_region[status] = terms_df_subset_status.groupby(['Region','SubRegion'])['CapacityInMtpa'].sum()

#fille NaN with 0.0
cap_by_region = cap_by_region.fillna(0)
cap_by_country = cap_by_country.fillna(0)

cap_by_region['In Development (Proposed + Construction)'] = cap_by_region[['Proposed','Construction']].sum(axis=1)
cap_by_country['In Development (Proposed + Construction)'] = cap_by_country[['Proposed','Construction']].sum(axis=1)

cap_by_country = cap_by_country[excel_status_list]
cap_by_region = cap_by_region[excel_status_list]

cap_by_region.index.names = ['Region','Subregion']
cap_by_country.index.name = 'Country'

cap_by_region.loc['Total',:] = cap_by_region.sum(axis=0).values
cap_by_country.loc['Total',:] = cap_by_country.sum(axis=0).values

cap_by_region = cap_by_region.loc[~(cap_by_region==0).all(axis=1)]

cap_by_region.replace(0,'',inplace=True)
cap_by_country.replace(0,'',inplace=True)

cap_by_region.to_excel(excel_writer, 'LNG export capacity by region')
cap_by_country.to_excel(excel_writer, 'LNG export capacity by country')

cap_by_region_export = cap_by_region.copy()

===country-level calculations===
Proposed
Construction
Shelved
Cancelled
Operating
Idle
Mothballed
Retired
===country-level calculations===
Proposed
Construction
Shelved
Cancelled
Operating
Idle
Mothballed
Retired

## owner analysis

In [65]:
# this cell takes the terminals data set (call it "terms_df_all", here we're using the indev terminals subset)
# and loops throw every row, breaks up the parent and % ownership strings,
# and outputs a dataframe owner_parent_calculations_df that has a bunch of different useful info related
# to parent shares, capacity, etc.
owner_parent_calculations_df = pandas.DataFrame() # empty df for storing owner/parent stuff

for idx,row in terms_df_touse.iterrows():
    parent_string = row.Parent #.values[0]

    # the two lines below go through the parent entries in the sheet and split them,
    # recording the percents and parents in separate lists, to be dealt with later
    parent_list = re.sub(' \[.*?\]', '', parent_string).split('; ') # all entries must have an "Owner [%]" syntax, so [unknown %] is included
    percent_list = [float(i.rstrip('%'))/100. for i in re.findall('\\d+(?:\\.\\d+)?%', parent_string)]

    # if there are fewer recorded percents than number of parents
    if parent_list.__len__()!=percent_list.__len__():
        # if there are no percents, make them all equal
        if percent_list==[]:
            percent_list = [1/parent_list.__len__() for i in parent_list]
        # otherwise, get the difference and distribute the remainder equally among remaining parents
        else:
            nmissing = parent_list.__len__()-percent_list.__len__()
            # distribute nans evenly
            total = numpy.nansum(percent_list)
            leftover = 1-total
            percent_list += [leftover/nmissing]*nmissing

    # now go through each parent and associated percent ownership
    # and store it alongside the project's name along with capacity, status, region, etc.
    # this is stored inside the big dataframe owner_parent_calculations_df
    for p_idx,parent in enumerate(parent_list):
        if parent not in parent_metadata_df.index.to_list():
            parent_metadata_df.loc[parent,'ParentHQCountry']='Unknown'
        owner_parent_calculations_df = pandas.concat([owner_parent_calculations_df, 
                                                      pandas.DataFrame([{'Parent':parent, 'ComboID':row.ComboID,
                                                                         'FractionOwnership':percent_list[p_idx],
                                                                         'PercentString':'{:.2f}%'.format(percent_list[p_idx]*100),
                                                                         'ParentHQCountry':parent_metadata_df.loc[parent_metadata_df.index==parent]['ParentHQCountry'].values[0],
                                                                         'ParentHQRegion':parent_metadata_df.loc[parent_metadata_df.index==parent]['ParentHQRegion'].values[0],
                                                                         'TerminalCountry':row.Country,
                                                                         'TerminalRegion':row.Region,
                                                                         'Status':row.Status,
                                                                         'Import/Export':row['Import/Export'],
                                                                         'CapacityInMtpa':row.CapacityInMtpa,
                                                                         'ProjectWiki':row.Wiki,
                                                                         'ProjectName':row.TerminalName+' '+str(row.UnitName)}])])

owner_parent_calculations_df.reset_index(drop=True, inplace=True)
owner_parent_calculations_df['CapacityOwnedInMtpa'] = owner_parent_calculations_df.FractionOwnership*owner_parent_calculations_df.CapacityInMtpa
owner_parent_calculations_df['ParentCapacityString'] = owner_parent_calculations_df.Parent + ' (' + owner_parent_calculations_df.CapacityOwnedInMtpa.round(1).astype(str).replace('nan','unknown') + ' mtpa)'

### ntrains export by parent company, project status

In [66]:
owners_ntrains_by_status_df = \
    owner_parent_calculations_df.loc[owner_parent_calculations_df['Import/Export']=='Export'].groupby(
    ['Parent','ParentHQCountry','Status']).agg({'Status':['count']}).unstack().droplevel(axis=1, level=[0,1])

owners_ntrains_by_status_df = owners_ntrains_by_status_df.reindex(columns=status_list)
owners_ntrains_by_status_df = owners_ntrains_by_status_df.reset_index().set_index('Parent')
owners_ntrains_by_status_df.columns.name = None

owners_ntrains_by_status_df['In Development (Proposed + Construction)'] = owners_ntrains_by_status_df[['Proposed','Construction']].sum(axis=1)

owners_ntrains_by_status_df = owners_ntrains_by_status_df.rename(columns={'Parent':'Parent Company',
                                                                          'ParentHQCountry':'Country'})
# rearrange the order of the columns for output
owners_ntrains_by_status_df = owners_ntrains_by_status_df[excel_status_list_with_countries]

# totals_row = owners_ntrains_by_status_df.sum(axis=0, min_count=0)
# totals_row.name = 'Total'
# owners_ntrains_by_status_df = owners_ntrains_by_status_df.append(totals_row)
owners_ntrains_by_status_df.loc['Total',:] = owners_ntrains_by_status_df.sum(axis=0, min_count=0).values
owners_ntrains_by_status_df.loc['Total','Country'] = ''

owners_ntrains_by_status_df = owners_ntrains_by_status_df.replace(numpy.nan, '')
owners_ntrains_by_status_df = owners_ntrains_by_status_df.replace(0, '')

owners_ntrains_by_status_df.to_excel(excel_writer, 'LNG export trains by owner')

### ntrains import by parent company, project status

In [67]:
owners_ntrains_by_status_df = \
    owner_parent_calculations_df.loc[owner_parent_calculations_df['Import/Export']=='Import'].groupby(
    ['Parent','ParentHQCountry','Status']).agg({'Status':['count']}).unstack().droplevel(axis=1, level=[0,1])

owners_ntrains_by_status_df = owners_ntrains_by_status_df.reindex(columns=status_list)
owners_ntrains_by_status_df = owners_ntrains_by_status_df.reset_index().set_index('Parent')
owners_ntrains_by_status_df.columns.name = None

owners_ntrains_by_status_df['In Development (Proposed + Construction)'] = owners_ntrains_by_status_df[['Proposed','Construction']].sum(axis=1)

owners_ntrains_by_status_df = owners_ntrains_by_status_df.rename(columns={'Parent':'Parent Company',
                                                                          'ParentHQCountry':'Country'})
# rearrange the order of the columns for output
owners_ntrains_by_status_df = owners_ntrains_by_status_df[excel_status_list_with_countries]

# totals_row = owners_ntrains_by_status_df.sum(axis=0, min_count=0)
# totals_row.name = 'Total'
# owners_ntrains_by_status_df = owners_ntrains_by_status_df.append(totals_row)
owners_ntrains_by_status_df.loc['Total',:] = owners_ntrains_by_status_df.sum(axis=0, min_count=0).values
owners_ntrains_by_status_df.loc['Total','Country'] = ''

owners_ntrains_by_status_df = owners_ntrains_by_status_df.replace(numpy.nan, '')
owners_ntrains_by_status_df = owners_ntrains_by_status_df.replace(0, '')

owners_ntrains_by_status_df.to_excel(excel_writer, 'LNG import trains by owner')

### capacity export by parent company, project status

In [68]:
owners_capacity_by_status_df = \
    owner_parent_calculations_df.loc[owner_parent_calculations_df['Import/Export']=='Export'].groupby(
    ['Parent','ParentHQCountry','Status']).agg({'CapacityInMtpa':['sum']}).unstack().droplevel(axis=1, level=[0,1])

owners_capacity_by_status_df = owners_capacity_by_status_df.reindex(columns=status_list)
owners_capacity_by_status_df = owners_capacity_by_status_df.reset_index().set_index('Parent')
owners_capacity_by_status_df.columns.name = None

owners_capacity_by_status_df['In Development (Proposed + Construction)'] = owners_capacity_by_status_df[['Proposed','Construction']].sum(axis=1)

owners_capacity_by_status_df = owners_capacity_by_status_df.rename(columns={'Parent':'Parent Company',
                                                                          'ParentHQCountry':'Country'})
# rearrange the order of the columns for output
owners_capacity_by_status_df = owners_capacity_by_status_df[excel_status_list_with_countries]

# totals_row = owners_capacity_by_status_df.sum(axis=0, min_count=0)
# totals_row.name = 'Total'
# owners_capacity_by_status_df = owners_capacity_by_status_df.append(totals_row)
owners_capacity_by_status_df.loc['Total',:] = owners_capacity_by_status_df.sum(axis=0, min_count=0).values
owners_capacity_by_status_df.loc['Total','Country'] = ''

owners_capacity_by_status_df = owners_capacity_by_status_df.replace(numpy.nan, '')
owners_capacity_by_status_df = owners_capacity_by_status_df.replace(0, '')

owners_capacity_by_status_df.to_excel(excel_writer, 'LNG export capacity by owner')

### capacity import by parent company, project status

In [69]:
owners_capacity_by_status_df = \
    owner_parent_calculations_df.loc[owner_parent_calculations_df['Import/Export']=='Import'].groupby(
    ['Parent','ParentHQCountry','Status']).agg({'CapacityInMtpa':['sum']}).unstack().droplevel(axis=1, level=[0,1])

owners_capacity_by_status_df = owners_capacity_by_status_df.reindex(columns=status_list)
owners_capacity_by_status_df = owners_capacity_by_status_df.reset_index().set_index('Parent')
owners_capacity_by_status_df.columns.name = None

owners_capacity_by_status_df['In Development (Proposed + Construction)'] = owners_capacity_by_status_df[['Proposed','Construction']].sum(axis=1)

owners_capacity_by_status_df = owners_capacity_by_status_df.rename(columns={'Parent':'Parent Company',
                                                                          'ParentHQCountry':'Country'})
# rearrange the order of the columns for output
owners_capacity_by_status_df = owners_capacity_by_status_df[excel_status_list_with_countries]

# totals_row = owners_capacity_by_status_df.sum(axis=0, min_count=0)
# totals_row.name = 'Total'
# owners_capacity_by_status_df = owners_capacity_by_status_df.append(totals_row)
owners_capacity_by_status_df.loc['Total',:] = owners_capacity_by_status_df.sum(axis=0, min_count=0).values
owners_capacity_by_status_df.loc['Total','Country'] = ''

owners_capacity_by_status_df = owners_capacity_by_status_df.replace(numpy.nan, '')
owners_capacity_by_status_df = owners_capacity_by_status_df.replace(0, '')

owners_capacity_by_status_df.to_excel(excel_writer, 'LNG import capacity by owner')

### no. of operating terminals by start year, facility type (1980–2021)

In [70]:
year_indices = list(range(1980,2023))

terms_by_start_year_df = pandas.DataFrame(0.0, index=year_indices, columns=['Import terminals', 'Export terminals'])

terms_started_df = terms_df_touse[(terms_df_touse['Status'].isin(['Operating'])) &
                              (terms_df_touse['Fuel']=='LNG') & (terms_df_touse['Import/Export']=='Import')]
terms_by_start_year_df['Import terminals'] = terms_started_df.groupby('StartYearEarliest').size()

terms_started_df = terms_df_touse[(terms_df_touse['Status'].isin(['Operating'])) &
                              (terms_df_touse['Fuel']=='LNG') & (terms_df_touse['Import/Export']=='Export')]
terms_by_start_year_df['Export terminals'] = terms_started_df.groupby('StartYearEarliest').size()

terms_by_start_year_df.index.name = 'Start year'

terms_by_start_year_df.loc['Total',:] = terms_by_start_year_df.sum(axis=0).values

terms_by_start_year_df.replace(numpy.nan,'',inplace=True)

terms_by_start_year_df.to_excel(excel_writer, 'LNG terminals by start year')

### capacity of operating terminals by start year, facility type (1980–2021)

In [71]:
year_indices = list(range(1980,2023))

capacity_by_start_year_df = pandas.DataFrame(0.0, index=year_indices, columns=['Import terminals', 'Export terminals'])

terms_started_df = terms_df_touse.loc[(terms_df_touse['Status'].isin(['Operating'])) &
                                      (terms_df_touse['Fuel']=='LNG') & 
                                      (terms_df_touse['Import/Export']=='Import')]
capacity_by_start_year_df['Import terminals'] = terms_started_df.groupby('StartYearEarliest')['CapacityInMtpa'].sum()

terms_started_df = terms_df_touse.loc[(terms_df_touse['Status'].isin(['Operating'])) &
                                      (terms_df_touse['Fuel']=='LNG') & 
                                      (terms_df_touse['Import/Export']=='Export')]
capacity_by_start_year_df['Export terminals'] = terms_started_df.groupby('StartYearEarliest')['CapacityInMtpa'].sum(min_count=0)

capacity_by_start_year_df.loc['Total',:] = capacity_by_start_year_df.sum(axis=0).values

capacity_by_start_year_df.index.name = 'Start year'
capacity_by_start_year_df.replace(numpy.nan,'',inplace=True)

# totals_row = capacity_by_start_year_df.sum(axis=0)
# totals_row.name = 'Total'
# capacity_by_start_year_df = capacity_by_start_year_df.append(totals_row)

capacity_by_start_year_df.to_excel(excel_writer, 'LNG capacity by start year')

# save excel file

In [52]:
excel_writer.close()

In [53]:
print(current_time)

2023-10-12_T114246

# sum export and import capacities

In [86]:
cap_by_region_total = cap_by_region_import.replace('',0).add(cap_by_region_export.replace('',0), fill_value=0)

In [87]:
cap_by_region_export.replace('',0)

                                          Proposed  Construction  \
Region   Subregion
Africa   Northern Africa                      0.00          0.07
         Sub-Saharan Africa                  55.82         13.92
Americas Latin America and the Caribbean     64.57          3.25
         Northern America                   358.62         36.11
Asia     Central Asia                         0.00          0.00
         South-eastern Asia                  11.50          5.80
         Southern Asia                        0.00          0.00
         Western Asia                        63.60          1.00
Europe   Eastern Europe                     113.40         21.10
         Northern Europe                      0.00          0.00
Oceania  Australia and New Zealand           20.10          0.00
         Melanesia                            8.00          0.00
Total                                       695.61         81.25

                                          In Development (Proposed + Construction)  \
Region   Subregion
Africa   Northern Africa                                                      0.07
         Sub-Saharan Africa                                                  69.74
Americas Latin America and the Caribbean                                     67.82
         Northern America                                                   394.73
Asia     Central Asia                                                         0.00
         South-eastern Asia                                                  17.30
         Southern Asia                                                        0.00
         Western Asia                                                        64.60
Europe   Eastern Europe                                                     134.50
         Northern Europe                                                      0.00
Oceania  Australia and New Zealand                                           20.10
         Melanesia                                                            8.00
Total                                                                       776.86

                                          Shelved  Cancelled  Operating  Idle  \
Region   Subregion
Africa   Northern Africa                     0.00       5.00      41.54   0.0
         Sub-Saharan Africa                 34.10      27.39      34.32   0.0
Americas Latin America and the Caribbean     0.00      21.60      16.45   0.0
         Northern America                   12.29     439.11      73.90  15.3
Asia     Central Asia                        0.00       0.00       0.20   0.0
         South-eastern Asia                  0.00       6.55      58.35   0.0
         Southern Asia                       0.00      74.75       0.00   0.0
         Western Asia                       22.00      13.04      95.40   0.0
Europe   Eastern Europe                     14.42      16.36      28.90   0.0
         Northern Europe                     0.00       0.00       4.68   0.0
Oceania  Australia and New Zealand           7.20      45.80      87.60   0.0
         Melanesia                           1.50       6.00       8.30   0.0
Total                                       91.51     655.60     449.64  15.3

                                          Mothballed  Retired
Region   Subregion
Africa   Northern Africa                        3.20      7.8
         Sub-Saharan Africa                     0.00      0.0
Americas Latin America and the Caribbean        3.75      0.0
         Northern America                       1.50      0.0
Asia     Central Asia                           0.00      0.0
         South-eastern Asia                     0.00     30.1
         Southern Asia                          0.00      0.0
         Western Asia                           7.20      0.0
Europe   Eastern Europe                         0.00      0.0
         Northern Europe                        0.00      0.0
Oceania  Australia and New Zealand              0.00      0.0
         Melanesia                              0.00      0.0
Total                                          15.65     37.9

In [88]:
cap_by_region_import.replace('',0)

                                          Proposed  Construction  \
Region   Subregion
Africa   Northern Africa                      5.15          0.00
         Sub-Saharan Africa                   6.88          1.70
Americas Latin America and the Caribbean     43.48         12.28
         Northern America                     0.05          0.00
Asia     Eastern Asia                       149.76         91.25
         South-eastern Asia                  76.84         21.66
         Southern Asia                       69.71         33.00
         Western Asia                         0.00          8.11
Europe   Eastern Europe                       8.82          1.54
         Northern Europe                     29.79          0.10
         Southern Europe                     44.71          4.04
         Western Europe                      56.10         17.39
Oceania  Australia and New Zealand            3.30          1.90
Total                                       494.59        192.97

                                          In Development (Proposed + Construction)  \
Region   Subregion
Africa   Northern Africa                                                      5.15
         Sub-Saharan Africa                                                   8.58
Americas Latin America and the Caribbean                                     55.76
         Northern America                                                     0.05
Asia     Eastern Asia                                                       241.01
         South-eastern Asia                                                  98.50
         Southern Asia                                                      102.71
         Western Asia                                                         8.11
Europe   Eastern Europe                                                      10.36
         Northern Europe                                                     29.89
         Southern Europe                                                     48.75
         Western Europe                                                      73.49
Oceania  Australia and New Zealand                                            5.20
Total                                                                       687.56

                                          Shelved  Cancelled  Operating  Idle  \
Region   Subregion
Africa   Northern Africa                     0.00      10.64       5.70   4.2
         Sub-Saharan Africa                  0.50       7.70       0.11   0.0
Americas Latin America and the Caribbean     6.46      24.97      73.46   0.0
         Northern America                    0.00     259.52      61.00  25.0
Asia     Eastern Asia                       25.80      54.49     444.10   0.0
         South-eastern Asia                  8.40      28.34      45.05   0.0
         Southern Asia                       8.38      80.95      65.20   0.0
         Western Asia                       11.10       8.00      72.10   7.6
Europe   Eastern Europe                      6.00       7.30       7.28   0.0
         Northern Europe                     2.75      23.56      39.80   0.0
         Southern Europe                     3.65      47.68      70.35   0.0
         Western Europe                      1.80      12.70      41.02   0.0
Oceania  Australia and New Zealand           0.00       1.75       0.00   0.0
Total                                       74.84     567.60     925.17  36.8

                                          Mothballed  Retired
Region   Subregion
Africa   Northern Africa                         0.0      0.0
         Sub-Saharan Africa                      0.0      0.0
Americas Latin America and the Caribbean         0.0      0.0
         Northern America                       45.0     17.3
Asia     Eastern Asia                            1.5      0.0
         South-eastern Asia                      0.0      0.0
         Southern Asia                           0.0      0.0
         Western Asia                            0.0      0.0
Europe   Eastern Europe                          0.0      0.0
         Northern Europe                         0.0      3.0
         Southern Europe                         0.0      0.0
         Western Europe                          0.0      0.0
Oceania  Australia and New Zealand               0.0      0.0
Total                                           46.5     20.3

In [89]:
cap_by_region_total#.replace(numpy.nan,'')

                                          Proposed  Construction  \
Region   Subregion
Africa   Northern Africa                      5.15          0.07
         Sub-Saharan Africa                  62.70         15.62
Americas Latin America and the Caribbean    108.05         15.53
         Northern America                   358.67         36.11
Asia     Central Asia                         0.00          0.00
         Eastern Asia                       149.76         91.25
         South-eastern Asia                  88.34         27.46
         Southern Asia                       69.71         33.00
         Western Asia                        63.60          9.11
Europe   Eastern Europe                     122.22         22.64
         Northern Europe                     29.79          0.10
         Southern Europe                     44.71          4.04
         Western Europe                      56.10         17.39
Oceania  Australia and New Zealand           23.40          1.90
         Melanesia                            8.00          0.00
Total                                      1190.20        274.22

                                          In Development (Proposed + Construction)  \
Region   Subregion
Africa   Northern Africa                                                      5.22
         Sub-Saharan Africa                                                  78.32
Americas Latin America and the Caribbean                                    123.58
         Northern America                                                   394.78
Asia     Central Asia                                                         0.00
         Eastern Asia                                                       241.01
         South-eastern Asia                                                 115.80
         Southern Asia                                                      102.71
         Western Asia                                                        72.71
Europe   Eastern Europe                                                     144.86
         Northern Europe                                                     29.89
         Southern Europe                                                     48.75
         Western Europe                                                      73.49
Oceania  Australia and New Zealand                                           25.30
         Melanesia                                                            8.00
Total                                                                      1464.42

                                          Shelved  Cancelled  Operating  Idle  \
Region   Subregion
Africa   Northern Africa                     0.00      15.64      47.24   4.2
         Sub-Saharan Africa                 34.60      35.09      34.43   0.0
Americas Latin America and the Caribbean     6.46      46.57      89.91   0.0
         Northern America                   12.29     698.63     134.90  40.3
Asia     Central Asia                        0.00       0.00       0.20   0.0
         Eastern Asia                       25.80      54.49     444.10   0.0
         South-eastern Asia                  8.40      34.89     103.40   0.0
         Southern Asia                       8.38     155.70      65.20   0.0
         Western Asia                       33.10      21.04     167.50   7.6
Europe   Eastern Europe                     20.42      23.66      36.18   0.0
         Northern Europe                     2.75      23.56      44.48   0.0
         Southern Europe                     3.65      47.68      70.35   0.0
         Western Europe                      1.80      12.70      41.02   0.0
Oceania  Australia and New Zealand           7.20      47.55      87.60   0.0
         Melanesia                           1.50       6.00       8.30   0.0
Total                                      166.35    1223.20    1374.81  52.1

                                          Mothballed  Retired
Region   Subregion
Africa   Northern Africa                        3.20      7.8
         Sub-Saharan Africa                     0.00      0.0
Americas Latin America and the Caribbean        3.75      0.0
         Northern America                      46.50     17.3
Asia     Central Asia                           0.00      0.0
         Eastern Asia                           1.50      0.0
         South-eastern Asia                     0.00     30.1
         Southern Asia                          0.00      0.0
         Western Asia                           7.20      0.0
Europe   Eastern Europe                         0.00      0.0
         Northern Europe                        0.00      3.0
         Southern Europe                        0.00      0.0
         Western Europe                         0.00      0.0
Oceania  Australia and New Zealand              0.00      0.0
         Melanesia                              0.00      0.0
Total                                          62.15     58.2